// ── Entity Types ─────────────────────────────────────────────────
export type {
  DynamoItem,
  NodeEntity,
  NodeStatus,
  NodeRole,
  SyncState,
  AdoptionStatus,
  VpnConfigSnapshot,
  ServerSnapshot,
  PeerSnapshot,
  PeerEntity,
  CreatePeerInput,
  UpdatePeerInput,
  VpnConfigEntity,
  VpnServerConfig,
  VpnPeerDefaults,
  IpPoolEntity,
  SystemConfigEntity,
  AuditLogEntity,
  AuditAction,
  WsConnectionEntity,
  PendingKeyEntity,
  DeviceEntity,
  DeviceType,
  DeviceStatus,
  ProvisionMethod,
} from "./entities.js";

export { DEFAULT_SYSTEM_CONFIG } from "./entities.js";

// ── Key Builders ─────────────────────────────────────────────────
export {
  nodeKey,
  peerKey,
  vpnConfigKey,
  ipPoolKey,
  systemConfigKey,
  auditKey,
  auditSortKey,
  wsConnectionKey,
  nodeRoleGsi1,
  peerServerGsi1,
  nodeStatusGsi2,
  nodeAdoptionCodeGsi3,
  pendingKeyKey,
  deviceKey,
  deviceNodeGsi1,
  deviceTokenGsi3,
  extractDeviceId,
  extractNodeId,
  extractPeerId,
  extractConnectionId,
  extractSubnetKey,
} from "./keys.js";

// ── Mappers ──────────────────────────────────────────────────────
export type {
  NodeInput,
  PeerInput,
  VpnConfigInput,
  IpPoolInput,
  SystemConfigInput,
  AuditLogInput,
  WsConnectionInput,
  PendingKeyInput,
  DeviceInput,
} from "./mappers.js";

export {
  toNodeItem,
  fromNodeItem,
  toPeerItem,
  fromPeerItem,
  toVpnConfigItem,
  fromVpnConfigItem,
  toIpPoolItem,
  fromIpPoolItem,
  toSystemConfigItem,
  fromSystemConfigItem,
  toAuditLogItem,
  fromAuditLogItem,
  toWsConnectionItem,
  fromWsConnectionItem,
  toPendingKeyItem,
  fromPendingKeyItem,
  toDeviceItem,
  fromDeviceItem,
} from "./mappers.js";
