#!/bin/sh
# install-spark.sh — set up a Bifrost spark on this host.
#
# The spark bridges an on-site UniFi network to your Bifrost control plane. This
# script creates /opt/bifrost-spark, drops a docker-compose using the published
# image, writes the config, and starts it. The spark then registers and waits —
# you confirm the connection in the dashboard (Sparks → Adopt) to bind it to
# your account.
#
# Run interactively:
#   curl -fsSL https://raw.githubusercontent.com/ASCtheone/bifrost/main/scripts/install-spark.sh | sh
# or non-interactively with env vars:
#   BIFROST_ADOPTION_CODE=XXX-XXX-XXX UNIFI_HOST=192.168.1.1 UNIFI_USER=bifrost \
#   UNIFI_PASS=secret sh install-spark.sh
set -eu

DIR="${BIFROST_SPARK_DIR:-/opt/bifrost-spark}"
IMAGE="${BIFROST_SPARK_IMAGE:-ghcr.io/asctheone/bifrost-spark:latest}"
MASTER="${BIFROST_MASTER:-https://dash.asc.ninja/bifrost/api}"

say() { printf '%s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || die "docker is required"
docker compose version >/dev/null 2>&1 || die "docker compose (v2) is required"

# ask VAR "prompt" [default] — reads from the terminal even under curl | sh.
ask() {
	var=$1; prompt=$2; def=${3:-}
	eval "cur=\${$var:-}"
	[ -n "${cur:-}" ] && return 0
	if [ -r /dev/tty ]; then
		printf '%s%s: ' "$prompt" "${def:+ [$def]}" >/dev/tty
		IFS= read -r ans </dev/tty || ans=""
		[ -z "$ans" ] && ans=$def
		eval "$var=\$ans"
	else
		eval "$var=\$def"
	fi
}

say "Installing a Bifrost spark into $DIR"
say "Get an adoption code from the dashboard: Sparks → Add Spark."
ask BIFROST_ADOPTION_CODE "Adoption code"
ask UNIFI_HOST  "UniFi controller IP/host" "192.168.1.1"
ask UNIFI_PORT  "UniFi port" "443"
ask UNIFI_SITE  "UniFi site" "default"
ask UNIFI_USER  "UniFi username"
ask UNIFI_PASS  "UniFi password"

[ -n "${BIFROST_ADOPTION_CODE:-}" ] || die "an adoption code is required"
[ -n "${UNIFI_USER:-}" ] || die "a UniFi username is required"

mkdir -p "$DIR"

umask 077
cat >"$DIR/bifrost-spark.toml" <<EOF
# Bifrost spark config — generated by install-spark.sh
master_url = "$MASTER"
adoption_code = "$BIFROST_ADOPTION_CODE"
poll_interval_seconds = 30

[unifi]
host = "$UNIFI_HOST"
port = $UNIFI_PORT
site = "$UNIFI_SITE"
username = "$UNIFI_USER"
password = "$UNIFI_PASS"
insecure = true
EOF
umask 022

cat >"$DIR/docker-compose.yml" <<EOF
services:
  bifrost-spark:
    image: $IMAGE
    volumes:
      - ./:/etc/bifrost      # bifrost-spark.toml + persisted spark-state.json
    restart: unless-stopped
EOF

say "Starting the spark…"
( cd "$DIR" && docker compose pull && docker compose up -d )

cat <<EOF

Spark installed and started in $DIR.

  Next: open your Bifrost dashboard → Sparks. The new spark appears as
  "available" — click Adopt to confirm the connection and bind it to your
  account. It will then manage the UniFi WireGuard server automatically.

  Logs:   cd $DIR && docker compose logs -f
  Update: cd $DIR && docker compose pull && docker compose up -d
  Remove: cd $DIR && docker compose down
EOF
