#!/bin/sh
# install-spark.sh — install *or update* a Bifrost spark on this host.
#
# The spark bridges an on-site UniFi network to your Bifrost control plane.
#
#   curl -fsSL .../install-spark.sh | sh -s -- <adoption-code>
#
# The dashboard hands you that exact line, code included (Sparks → Add Spark, or the
# copy button on any spark).
#
# On first run it asks how you want it installed:
#
#   docker  — a container via docker compose. Offers to install Docker if missing.
#   native  — a static binary + a systemd service. No Docker at all.
#
# Re-run the same command any time to UPDATE. The choice is recorded in
# <dir>/install.conf, so an update never re-asks anything — it just pulls the new
# version and restarts. (An update doesn't even need the adoption code: the spark's
# node key is already persisted.)
#
# The UniFi controller is NOT configured here. It is set in the dashboard
# (Sparks → your spark → UniFi) and delivered to the spark over its authenticated
# channel — so controller credentials never have to be typed onto each box.
#
# Non-interactive: BIFROST_MODE=docker|native BIFROST_ADOPTION_CODE=XXX-XXX-XXX
# Env overrides: BIFROST_SPARK_DIR, BIFROST_SPARK_IMAGE, BIFROST_MASTER, BIFROST_REPO
set -eu

# Adoption code may come as the first argument (`sh -s -- CODE`) or via the env.
[ $# -gt 0 ] && [ -n "${1:-}" ] && BIFROST_ADOPTION_CODE="$1"

DIR="${BIFROST_SPARK_DIR:-/opt/bifrost-spark}"
IMAGE="${BIFROST_SPARK_IMAGE:-ghcr.io/asctheone/bifrost-spark:latest}"
MASTER="${BIFROST_MASTER:-https://dash.asc.ninja/bifrost/api}"
REPO="${BIFROST_REPO:-ASCtheone/bifrost}"
DL="https://github.com/$REPO/releases/latest/download"

CONF="$DIR/install.conf"        # records the mode, so updates don't re-ask
TOML="$DIR/bifrost-spark.toml"  # the spark's own config (+ its state file, alongside)
BIN=/usr/local/bin/bifrost-spark
UNIT=/etc/systemd/system/bifrost-spark.service

say()  { printf '%s\n' "$*"; }
warn() { printf 'warning: %s\n' "$*" >&2; }
die()  { printf 'error: %s\n' "$*" >&2; exit 1; }

# Read from the terminal even when the script arrives via `curl | sh` (in which
# case stdin is the script, not the user). Skips if the var is already set.
ask() {
	var=$1 prompt=$2 def=${3:-}
	eval "cur=\${$var:-}"
	[ -n "${cur:-}" ] && return 0
	if [ -r /dev/tty ]; then
		printf '%s%s: ' "$prompt" "${def:+ [$def]}" >/dev/tty
		IFS= read -r ans </dev/tty || ans=""
		[ -z "$ans" ] && ans=$def
		eval "$var=\$ans"
	else
		[ -n "$def" ] || die "$prompt is required (no terminal; set it via env)"
		eval "$var=\$def"
	fi
}

need_root() {
	[ "$(id -u)" = 0 ] && return 0
	command -v sudo >/dev/null 2>&1 || die "run as root (or install sudo)"
	SUDO=sudo
}
SUDO=""

have_docker() { command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; }

fetch() { # fetch <url> <dest>
	if command -v curl >/dev/null 2>&1; then
		curl -fsSL "$1" -o "$2"
	elif command -v wget >/dev/null 2>&1; then
		wget -qO "$2" "$1"
	else
		die "need curl or wget"
	fi
}

# ── mode ────────────────────────────────────────────────────────

# An existing install decides its own mode. This is what makes re-running the
# one-liner an update rather than a re-interrogation.
load_mode() {
	[ -f "$CONF" ] || return 1
	# shellcheck disable=SC1090
	. "$CONF"
	[ -n "${MODE:-}" ]
}

choose_mode() {
	[ -n "${BIFROST_MODE:-}" ] && { MODE=$BIFROST_MODE; return 0; }
	if have_docker; then
		say "Docker is installed on this host."
		docker_hint="docker (detected)"
	else
		say "Docker is not installed."
		docker_hint="docker (will be installed)"
	fi
	say ""
	say "How should the spark run?"
	say "  1) $docker_hint — container, managed by docker compose"
	say "  2) native            — static binary + systemd service, no Docker"
	say ""
	ask PICK "Choose 1 or 2" "1"
	case "$PICK" in
		1 | docker) MODE=docker ;;
		2 | native) MODE=native ;;
		*) die "invalid choice: $PICK" ;;
	esac
}

# ── config (first install only) ─────────────────────────────────

write_config() {
	say ""
	say "Get an adoption code from the dashboard: Sparks → Add Spark."
	ask BIFROST_ADOPTION_CODE "Adoption code"
	[ -n "${BIFROST_ADOPTION_CODE:-}" ] || die "an adoption code is required"

	# No UniFi section: the controller is configured in the dashboard and delivered
	# to the spark over its authenticated channel. Nothing to type in here.
	$SUDO mkdir -p "$DIR"
	umask 077
	$SUDO sh -c "cat > '$TOML'" <<EOF
# Bifrost spark config — generated by install-spark.sh
# The UniFi controller is configured in the dashboard: Sparks → this spark → UniFi.
master_url = "$MASTER"
adoption_code = "$BIFROST_ADOPTION_CODE"
poll_interval_seconds = 30
EOF
	$SUDO chmod 0600 "$TOML"
	umask 022
}

save_mode() {
	$SUDO mkdir -p "$DIR"
	$SUDO sh -c "printf 'MODE=%s\n' '$MODE' > '$CONF'"
}

# ── docker ──────────────────────────────────────────────────────

install_docker() {
	have_docker && return 0
	say "Installing Docker…"
	command -v curl >/dev/null 2>&1 || die "need curl to install Docker"
	curl -fsSL https://get.docker.com | $SUDO sh || die "Docker install failed"
	$SUDO systemctl enable --now docker 2>/dev/null || true
	have_docker || die "Docker installed but 'docker compose' is unavailable"
}

setup_docker() {
	install_docker
	$SUDO sh -c "cat > '$DIR/docker-compose.yml'" <<EOF
services:
  bifrost-spark:
    image: $IMAGE
    volumes:
      - ./:/etc/bifrost      # bifrost-spark.toml + persisted spark-state.json
    restart: unless-stopped
EOF

	# The image is public, so the pull needs no credentials. But if this host ever
	# ran `docker login ghcr.io` and that token has since expired or been revoked,
	# Docker sends it anyway instead of asking for an anonymous token, and the
	# registry answers `denied` — on an image anyone else can pull freely.
	#
	# Note we run docker under sudo, so the credential that matters is ROOT's
	# (/root/.docker/config.json), not the invoking user's. `docker logout` as
	# yourself does not fix it, which makes this genuinely confusing to hit.
	#
	# Drop the stale credential and retry once, rather than surfacing a bare
	# "denied" that says nothing about the cause.
	if ! ( cd "$DIR" && $SUDO docker compose pull ); then
		warn "pull failed — retrying without any stored ghcr.io credentials"
		$SUDO docker logout ghcr.io >/dev/null 2>&1 || true
		( cd "$DIR" && $SUDO docker compose pull ) || die \
			"could not pull $IMAGE. The image is public, so this is usually a stale
       credential: try 'sudo docker logout ghcr.io' and re-run. If you need this
       host logged in to ghcr.io, re-login with a valid token."
	fi
	( cd "$DIR" && $SUDO docker compose up -d )
}

# ── native (static binary + systemd) ────────────────────────────

setup_native() {
	command -v systemctl >/dev/null 2>&1 || die "native mode needs systemd (use docker mode instead)"

	arch=$(uname -m)
	case "$arch" in
		x86_64 | amd64) asset=bifrost-spark-x86_64-linux ;;
		aarch64 | arm64) asset=bifrost-spark-aarch64-linux ;;
		*) die "no prebuilt spark binary for $arch (use docker mode)" ;;
	esac

	tmp=$(mktemp -d)
	trap 'rm -rf "$tmp"' EXIT
	say "Downloading $asset…"
	fetch "$DL/$asset" "$tmp/$asset" || die "download failed"

	# Verify against the release checksums — this binary runs as root, so a
	# corrupted or tampered download must not be installed silently.
	if fetch "$DL/SHA256SUMS" "$tmp/SHA256SUMS" 2>/dev/null && command -v sha256sum >/dev/null 2>&1; then
		want=$(awk -v a="$asset" '$2 == a || $2 == "*" a { print $1 }' "$tmp/SHA256SUMS" | head -n1)
		got=$(sha256sum "$tmp/$asset" | awk '{print $1}')
		[ -n "$want" ] || die "no checksum for $asset in SHA256SUMS"
		[ "$want" = "$got" ] || die "checksum mismatch for $asset (expected $want, got $got)"
		say "Checksum OK."
	else
		warn "could not verify the download checksum"
	fi

	$SUDO install -m 0755 "$tmp/$asset" "$BIN"

	$SUDO sh -c "cat > '$UNIT'" <<EOF
[Unit]
Description=Bifrost spark (on-site UniFi bridge)
After=network-online.target
Wants=network-online.target

[Service]
Environment=BIFROST_SPARK_CONFIG=$TOML
ExecStart=$BIN
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
	$SUDO systemctl daemon-reload
	$SUDO systemctl enable --now bifrost-spark
	$SUDO systemctl restart bifrost-spark
}

# On an existing install, honour an adoption code that differs from the stored one.
#
# The dashboard's Reinstall mints a fresh code and revokes the spark's node key, so
# the one-liner you copy afterwards carries a NEW code. Without this, the update path
# would skip write_config, leave the old (now dead) code in place, and keep the old
# node key — and the spark would sit there re-authenticating with a revoked key,
# never re-registering, with nothing in the UI to explain why.
#
# Only on a *different* code: re-running with the same one (or none) must not disturb
# a healthy spark, which is the whole point of the update path.
adopt_new_code() {
	cur=$(sed -n 's/^adoption_code *= *"\(.*\)"/\1/p' "$TOML" 2>/dev/null | head -n1)
	[ -n "${BIFROST_ADOPTION_CODE:-}" ] || return 0
	[ "$BIFROST_ADOPTION_CODE" != "$cur" ] || return 0

	say "New adoption code supplied — re-registering this spark."
	$SUDO sh -c "sed -i 's|^adoption_code *=.*|adoption_code = \"$BIFROST_ADOPTION_CODE\"|' '$TOML'"
	# The old node key was revoked when the code was reissued; drop the adoption
	# state so the spark registers again instead of retrying a dead credential.
	$SUDO rm -f "$DIR/spark-state.json"
}

# ── main ────────────────────────────────────────────────────────

need_root

if load_mode; then
	UPDATING=1
	say "Existing spark install found in $DIR (mode: $MODE) — updating."
	adopt_new_code
else
	UPDATING=0
	choose_mode
fi

[ "$UPDATING" = 0 ] && write_config
save_mode

case "$MODE" in
	docker) setup_docker ;;
	native) setup_native ;;
	*) die "unknown mode '$MODE' in $CONF" ;;
esac

if [ "$UPDATING" = 1 ]; then
	say ""
	say "Spark updated ($MODE)."
	exit 0
fi

cat <<EOF

Spark installed and started in $DIR (mode: $MODE).

  Next, in your Bifrost dashboard → Sparks:
    1. The new spark shows as "available" — click Adopt to bind it to your account.
    2. Open it and fill in the UniFi tab (controller host, user, password).
       The spark idles until you do; it picks the settings up on its next poll.

  Update: re-run this same one-liner. It won't ask anything again.
EOF

if [ "$MODE" = docker ]; then
	cat <<EOF
  Logs:   cd $DIR && docker compose logs -f
  Remove: cd $DIR && docker compose down
EOF
else
	cat <<EOF
  Logs:   journalctl -u bifrost-spark -f
  Remove: systemctl disable --now bifrost-spark && rm -f $UNIT $BIN
EOF
fi
