package tray

import (
	"encoding/binary"
	"testing"
)

// TestBuildICOHeader validates the generated bytes are a well-formed single-image
// 32x32 32-bpp ICO, so Windows will accept SetIcon without silently failing.
func TestBuildICOHeader(t *testing.T) {
	ico := iconConnected()
	if len(ico) < 22+40 {
		t.Fatalf("icon too small: %d bytes", len(ico))
	}
	if binary.LittleEndian.Uint16(ico[0:2]) != 0 {
		t.Fatalf("reserved field must be 0")
	}
	if binary.LittleEndian.Uint16(ico[2:4]) != 1 {
		t.Fatalf("type must be 1 (icon)")
	}
	if binary.LittleEndian.Uint16(ico[4:6]) != 1 {
		t.Fatalf("count must be 1")
	}
	if ico[6] != iconSize || ico[7] != iconSize {
		t.Fatalf("dimensions must be %dx%d, got %dx%d", iconSize, iconSize, ico[6], ico[7])
	}
	if bpp := binary.LittleEndian.Uint16(ico[12:14]); bpp != 32 {
		t.Fatalf("expected 32 bpp, got %d", bpp)
	}
	offset := binary.LittleEndian.Uint32(ico[18:22])
	if offset != 22 {
		t.Fatalf("image offset must be 22, got %d", offset)
	}
	// The DIB header height must be double the icon height (XOR + AND masks).
	dibHeight := int32(binary.LittleEndian.Uint32(ico[offset+8 : offset+12]))
	if dibHeight != iconSize*2 {
		t.Fatalf("DIB height must be %d, got %d", iconSize*2, dibHeight)
	}
}

func TestIconVariantsDistinct(t *testing.T) {
	c, i := iconConnected(), iconIdle()
	if len(c) != len(i) {
		t.Fatalf("icons should be the same size")
	}
	same := true
	for k := range c {
		if c[k] != i[k] {
			same = false
			break
		}
	}
	if same {
		t.Fatal("connected and idle icons should differ in colour")
	}
}
